### 회원 등록 (POST)
POST http://localhost:9999/members
Content-Type: application/json

{
  "memberName": "홍길동33"
}

### 회원 목록 조회 (GET)
GET http://localhost:9999/members
Accept: application/json

### 회원 단건 조회 (GET)
GET http://localhost:9999/members/1
Accept: application/json

### 회원 삭제 (DELETE)
DELETE http://localhost:9999/members/1
