plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.zz9z9.blogcode.springbatch.in.action'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-batch:3.5.5")
    runtimeOnly "org.hsqldb:hsqldb"   // HyperSQL Database 추가
}

test {
    useJUnitPlatform()
}